{% set name = "turbo_turtle" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl-aea/turbo-turtle/archive/refs/tags/{{ version }}.tar.gz
  sha256: a54ce887c5316f96b7057a9d15d7f594c180867f50a0c48af9f9f8d4de603490

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - turbo-turtle = turbo_turtle._main:main

requirements:
  host:
    - python {{ python_min }}
    - python-build
    - pip
    - pytest
    - lazy_loader >=0.4
    - scons >=4
    - setuptools >=64
    - setuptools_scm >=8
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx-book-theme
    - sphinxcontrib-bibtex
    - waves >=0.11.0
  run:
    - python >={{ python_min }}
    - lazy_loader >=0.4
    - scons >=4
    - waves >=0.11.0

test:
  requires:
    - pip
    - pytest
    - pytest-xdist
    - python {{ python_min }}
  imports:
    - turbo_turtle

about:
  home: https://github.com/lanl-aea/turbo-turtle
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved models
  description: |
    Turbo-Turtle (LANL code O4765) is a solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved
    models.
  doc_url: https://lanl-aea.github.io/turbo-turtle/index.html
  dev_url: https://github.com/lanl-aea/turbo-turtle

extra:
  recipe-maintainers:
    - kbrindley
    - tprobertslanl
