{% set name = "turbo_turtle" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl-aea/turbo-turtle/archive/refs/tags/{{ version }}.tar.gz
  sha256: e89f218c8d95484f3b0b8b61427c0bd82779226301436c991535966bac4d140d

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - turbo-turtle = turbo_turtle._main:main

requirements:
  host:
    - python
    - python-build
    - pip
    - lazy_loader >=0.4
    - scons >=4
    - setuptools >=64
    - setuptools_scm >=8
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx_rtd_theme >=1
    - sphinxcontrib-bibtex
    - waves >=0.7.2,<0.11.0
  run:
    - python >=3.8
    - lazy_loader >=0.4
    - scons >=4
    - waves >=0.7.2,<0.11.0

test:
  requires:
    - pip
    - pytest
    - pytest-xdist
  imports:
    - turbo_turtle

about:
  home: https://github.com/lanl-aea/turbo-turtle
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved models
  description: |
    Turbo-Turtle (LANL code O4765) is a solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved
    models.
  doc_url: https://lanl-aea.github.io/turbo-turtle/index.html
  dev_url: https://github.com/lanl-aea/turbo-turtle

extra:
  recipe-maintainers:
    - kbrindley
    - tprobertslanl
